[workspace]
authors = ["Scott A. Socolofsky <socolofs@tamu.edu>",
           "Chris Barker <chris.barker@noaa.gov>"
           ]
channels = ["conda-forge"]
name = "tamoc-dev"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "1.0.0"

[dependencies]
python = ">=3.10,<3.14"
numpy = ">=2.0,<2.4"
scipy = "*"
# optional I/O libs
netcdf4 = ">=1.7.4,<2"
xarray = "*"
pandas = "*"
openpyxl = "*"

[feature.build.dependencies]
compilers = "*"  # for fortran
meson = ">=1.5.0"
meson-python = ">=0.15.0"
ninja = ">=1.13.2,<2" # conda ninja package is only ninja, not the python wrapper
# ninja-python = ">=1.13.2,<2"
pkg-config = ">=0.29.2,<0.30"
pip = "*"
python-build = "*"

[feature.dev.dependencies]
matplotlib = "*"
ipython = "*"
jupyter = "*"

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.py310.dependencies]
python = "~=3.10.0"

[feature.py311.dependencies]
python = "~=3.11.0"


[feature.py312.dependencies]
python = "~=3.12.0"


[feature.py313.dependencies]
python = "~=3.13.0"


[environments]
# using the oldest supported python version for the default
default = { features = ["py310", "dev", "test", "build"], solve-group = "default" }
dev310 = ["py310", "dev", "test", "build"]
dev311 = ["py311", "dev", "test", "build"]
dev312 = ["py312", "dev", "test", "build"]
dev313 = ["py313", "dev", "test", "build"]
build310 = ["py310", "build"]
build311 = ["py311", "build"]
build312 = ["py312", "build"]
build313 = ["py313", "build"]
test310 = [ "py310", "test", "build" ]
test311 = [ "py311", "test", "build" ]
test312 = [ "py312", "test", "build" ]
test313 = [ "py313", "test", "build" ]

[tasks]
# build_wheel = {cmd = "python -m build --skip-dependency-check --no-isolation ./", default-environment = "build310"}
# we should be running no-isolation, but we need ninja-python to be intstalled
# and pixi can't seem to get it from conda-forge ???
build_wheel = {cmd = "python -m build ./", default-environment = "build310"}

# no-deps because force-reinstall re-installs ALL pacakges.
install = { cmd = "pip install --no-deps --root-user-action=ignore --force-reinstall --no-index --find-links=./dist/  tamoc", depends-on = ["build_wheel"]}

test = { cmd = "pytest tamoc/test/", depends-on = ["install"]}
